export const breeds = [
    'Labrador Retriever',
    'German Shepherd',
    'Golden Retriever',
    'French Bulldog',
    'Bulldog',
    'Poodle',
    'Beagle',
    'Rottweiler',
    'Yorkshire Terrier',
    'Dachshund',
    'Boxer',
    'Shih Tzu',
    'Siberian Husky',
    'Doberman Pinscher',
    'Great Dane',
    'Chihuahua',
    'Pomeranian',
    'Border Collie',
    'Australian Shepherd',
    'Cavalier King Charles Spaniel',
    'Shetland Sheepdog',
    'Akita',
    'Basset Hound',
    'Bichon Frise',
    'Boston Terrier',
    'Bullmastiff',
    'Cane Corso',
    'Chow Chow',
    'Cocker Spaniel',
    'Collie',
    'Dalmatian',
    'English Springer Spaniel',
    'Flat-Coated Retriever',
    'German Shorthaired Pointer',
    'Irish Setter',
    'Jack Russell Terrier',
    'Japanese Chin',
    'Keeshond',
    'Kuvasz',
    'Lhasa Apso',
    'Maltese',
    'Newfoundland',
    'Norwegian Elkhound',
    'Papillon',
    'Pug',
    'Rhodesian Ridgeback',
    'Saluki',
    'Samoyed',
    'Scottish Terrier',
    'Shar-Pei',
    'Shiba Inu',
    'Staffordshire Bull Terrier',
    'Tibetan Mastiff',
    'Vizsla',
    'Weimaraner',
    'Whippet',
    'Afghan Hound',
    'Airedale Terrier',
    'American Eskimo Dog',
    'American Staffordshire Terrier',
    'Basenji',
    'Belgian Malinois',
    'Bernese Mountain Dog',
    'Borzoi',
    'Brussels Griffon',
    'Cardigan Welsh Corgi',
    'Chinese Crested',
    'Dogo Argentino',
    'English Bulldog',
    'English Foxhound',
    'Finnish Spitz',
    'Greater Swiss Mountain Dog',
    'Havanese',
    'Ibizan Hound',
    'Irish Wolfhound',
    'Italian Greyhound',
    'Japanese Spitz',
    'Komondor',
    'Leonberger',
    'Lowchen',
    'Manchester Terrier',
    'Miniature Schnauzer',
    'Neapolitan Mastiff',
    'Norwich Terrier',
    'Old English Sheepdog',
    'Otterhound',
    'Pekingese',
    'Portuguese Water Dog',
    'Puggle',
    'Redbone Coonhound',
    'Schipperke',
    'Sealyham Terrier',
    'Sesame Shiba Inu',
    'Shetland Sheepdog',
    'Sloughi',
    'Soft-Coated Wheaten Terrier',
    'Spanish Water Dog',
    'Spinone Italiano',
    'Standard Schnauzer',
    'Tervuren',
    'Tibetan Spaniel',
    'Treeing Walker Coonhound',
    'Welsh Springer Spaniel',
  ];
  

  